<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMiuYbBu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMiuYbBu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerMiuYbBu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerMiuYbBu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerMiuYbBu\srcApp_KernelDevDebugContainer(array(
    'container.build_hash' => 'MiuYbBu',
    'container.build_id' => '5ea7f635',
    'container.build_time' => 1544117202,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMiuYbBu');
